name: Indexer Testing

on:
  pull_request:
    paths:
      - 'indexer/**'

jobs:
  indexer:
    name: indexer
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap

    - name: Run Indexer tests
      run: ./build/run indexer:test
